services:
  webapp:
    container_name: webapp-prod
    image: ft_transcendence:prod
    build:
      context: .
      dockerfile: Dockerfile
    command: bun start
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=production
      - HOST=${WEBAPP_HOST:?}
      - DATABASE_URL=postgres://${POSTGRES_USER:?}:${POSTGRES_PASSWORD:?}@db:5432/app
      - PRESENCE_DB_URL=redis://presence-db:6379
      - STORAGE_PUBLIC_ENDPOINT=https://${STORAGE_HOST:?}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:?}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:?}

  proxy:
    container_name: proxy-prod
    image: nginx:latest
    depends_on:
      webapp:
        condition: service_started
      storage:
        condition: service_started
    environment:
      WEBAPP_HOST: ${WEBAPP_HOST:?}
      STORAGE_HOST: ${STORAGE_HOST:?}
    volumes:
      - ./nginx/entrypoints/:/docker-entrypoint.d/99-user-scripts/:ro
      - ./nginx/templates/:/etc/nginx/templates/:ro
      - .secrets/ssl_certs:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"

  db:
    container_name: db-prod
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10

  storage:
    container_name: storage-prod
    image: ft_transcendence:minio
    build:
      context: ./submodules/minio
      dockerfile: ../../Dockerfile.minio
    command: server /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?}
    volumes:
      - storage_data:/data

  presence-db:
    container_name: redis-prod
    image: redis:8.4
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  migrate:
    container_name: migrate-prod
    image: ft_transcendence:migrate
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate-env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${POSTGRES_USER:?}:${POSTGRES_PASSWORD:?}@db:5432/app
  
volumes:
  db_data:
  storage_data:
