packages:
  - frontend
  - backend
  - packages/*

onlyBuiltDependencies:
  - "@bufbuild/buf"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild

syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true
