name: Lint Proto

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - ./.github/workflows/lint-buf.yml
      - buf.yaml
      - buf.gen.yaml
      - "**/*.proto"

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          push: false
          push_disable_create: true
