name: Lint Codestyle

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - ./.github/workflows/lint-codestyle.yml
      - biome.json
      - "frontend/**/*.js"
      - "frontend/**/*.ts"
      - "frontend/**/*.css"
      - "backend/**/*.js"
      - "backend/**/*.ts"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Run Script
        run: pnpm lint:codestyle
