name: Test

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - .github/workflows/build.yml
      - ".nvmrc"
      - "**/*.ts"
      - "**/*.js"
      - "**/*.yaml"
      - "**/*.proto"
      - "**/*.json"
      - "!**/biome.json"

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Run test
        run: pnpm test

      - name: Report coverage
        if: ${{ success() || failure() }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: ./.coverage/coverage-summary.json
          json-final-path: ./.coverage/coverage-final.json
