name: Test

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - .github/workflows/build.yml
      - ".nvmrc"
      - "**/*.ts"
      - "**/*.js"
      - "**/*.yaml"
      - "**/*.proto"
      - "**/*.json"
      - "!**/biome.json"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Build
        run: pnpm -r test
